server:
  port: 8080
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-user
            uri: http://k8s-backend-user-service:8080
            predicates:
              - Path=/api/user/**
            filters:
              - AddAuthenticationHeader
          - id: backend-alim
            uri: http://k8s-backend-alim-service:8080
            predicates:
              - Path=/api/alim/**
            filters:
              - AddAuthenticationHeader
          - id: backend-post
            uri: http://k8s-backend-post-service:8080
            predicates:
              - Path=/api/post/**
            filters:
              - AddAuthenticationHeader
jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G